In [2]:
import numpy as np

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

In [5]:
jay = np.array([[1, 2, 3], [4, 5, 6]])
print(jay)

[[1 2 3]
 [4 5 6]]


In [6]:
j1 = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20],[21,22,23,24,25,26,27,28,29,30]])

In [7]:
j1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [39]:
np.__version__



'2.4.1'

In [40]:
type(jay)

numpy.ndarray

In [42]:
a = np.array(45)
b= np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

a.ndim
b.ndim
c.ndim
d.ndim

3

In [16]:
a.ndim
b.ndim

1

In [19]:
f = np.array([1,2,3,4] , ndmin=2)
f

array([[1, 2, 3, 4]])

In [23]:
jay[1] * jay[0]

array([ 4, 10, 18])

In [24]:
j1[1] * j1[0]

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [32]:
c[1 ,2]

np.int64(6)