In [3]:
import numpy as np

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

In [6]:
jay = np.array([[1, 2, 3], [4, 5, 6]])
print(jay)

[[1 2 3]
 [4 5 6]]


In [20]:
j1 = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20],[21,22,23,24,25,26,27,28,29,30]])

In [21]:
j1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [22]:
np.__version__



'2.4.1'

In [23]:
type(jay)

numpy.ndarray

In [24]:
a = np.array(45)
b= np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

a.ndim
b.ndim
c.ndim
d.ndim

3

In [25]:
a.ndim
b.ndim

1

In [26]:
f = np.array([1,2,3,4] , ndmin=2)
f

array([[1, 2, 3, 4]])

In [27]:
jay[1] * jay[0]

array([ 4, 10, 18])

In [28]:
j1[1] * j1[0]

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [29]:
c[1 ,2]

np.int64(6)

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)
arr

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
jay.shape

(2, 3)

In [52]:
n1= np.array([[1,2,3,4,5,6],[7,8,9,10,11,120]])
g=n1.reshape(3,4)
g
h = np.hsplit(g,2)
h
c = np.concatenate(h)
c

array([[  1,   2],
       [  5,   6],
       [  9,  10],
       [  3,   4],
       [  7,   8],
       [ 11, 120]])